module.exports = {
    VIDEO_URL: "VIDEO_URL",
    VIDEO_URL_SENT: "VIDEO_URL_SENT",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VERIFY_USER: "VERIFY_USER",
    LOGOUT: "LOGOUT"
}